=== Myukies/University/Web Technologies/HTML/Practicals/Practical-6/catalog-internal.dtd
<!ELEMENT catalog (book+)>
<!ELEMENT book (title, author, year)>
<!ATTLIST book
          id ID #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== Myukies/University/Web Technologies/HTML/Practicals/Practical-6/data.xml
<?xml version="1.0"?>
<!DOCTYPE catalog SYSTEM "catalog-internal.dtd">
<catalog>
  <book id="001">
    <title>The Great Gatsby</title>
    <author>F. Scott Fitzgerald</author>
    <year>1925</year>
  </book>
  <book id="002">
    <title>To Kill a Mockingbird</title>
    <author>Harper Lee</author>
    <year>1960</year>
  </book>
</catalog>
